language: node_js

node_js:
  - "0.10"

before_install:
  - npm install

script:
  - npm test

notifications:
  slack:
    secure: TnJJ73pvonO8+FH3nCRiLOcDQkpqcJRP9j5wIWpEpTJl4Bz8QdJ3MJ3+PTvylodcEeNGEroObuqSk6rHFQvFYTpnVjvGGsdgQedHXlO6Z2eeOgB1IH7z+HIIA9h8VBMW8CVhsKnkvRDDttApuXoe84aVgPKECXaFS7llQFqTg0tGFUuyPE3Hb98NJ3ktdusD3HnhI2ypvR/sVV2bqKFkGjt2QA3qPCk8qa6Ytn8YNr6IOe2QKQyjPoU42VU9VrSWUXQP0ApEJWH3IZKHFSNqV4LI8t664vd92lAsjyclPyWetk+O4B7NWVPXDGduIA60oSx0qupUwOfC4JurUCEwo5anyHaQAEw+ydyyX0n8oIJRuM1PTjLb0HEmhLpgPUjOk1NSWyT7xCunEp/B4XOwMFSvZ4gTNIFVnfRgCHeJHXl3ki2pi8H27XHM9vYQICa0tM90ri+NBz5cjQcqW+n/6YQkCW57XI5jdBE4Zctkrj5FCDkbiez8zW3Zvq++RXJSYNLlzWBRamouEjsj8Eejfn2VbE2TSl497aSDuc5YDDqRfJs/XBfGmnEmz35cX0QYmOWyBlSA6s0td+UNowQ2kGJriIEUPY+hIQLvyaI5/I7XyZgKWGLKmW+Q4ApbkesCU4e0GWYfd8Hx0S1QsZU7MjxSjakbu5MSki5HDy0mwRg=
  email: false
